apiVersion: v1
kind: Service
metadata:
  name: k8s-sales-service
spec:
  type: ClusterIP
  selector:
    app: cloud-sigma-sales
  ports:
  - port: 50052
    targetPort: 50052

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-sigma-sales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-sigma-sales
  template:
    metadata:
      labels:
        app: cloud-sigma-sales
    spec:
      containers:
      - name: cloud-sigma-sales
        image: khaledhadjali/cloud_sigma_sales:latest
        env:
          - name: POSTGRES_DB
            value: cloud_sigma
          - name: POSTGRES_USER
            value: cloud_sigma
          - name: POSTGRES_PASSWORD
            value: cloud_sigma
          - name: DATABASE_URL
            value: postgres-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "256m"
        ports:
        - containerPort: 50052